# Generated by Django 2.0.2 on 2019-12-21 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(default='')),
                ('profile_image', models.TextField(default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.Profile')),
            ],
            options={
                'verbose_name_plural': 'Public',
            },
        ),
    ]
