# Generated by Django 2.0.2 on 2019-12-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20191223_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Profile'),
        ),
    ]
