# Generated by Django 2.0.2 on 2020-03-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20191226_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='qr_code',
            field=models.TextField(default=''),
        ),
    ]
