# Generated by Django 2.0.2 on 2020-03-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_publicstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicstore',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='publicstore',
            name='created_at',
            field=models.IntegerField(default=0),
        ),
    ]
