# Generated by Django 2.0.2 on 2020-03-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_profile_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'public'), (1, 'superadmin'), (2, 'storeowner')], default=0),
        ),
    ]
