# Generated by Django 2.0.2 on 2019-12-21 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('slogan', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.IntegerField(default=0)),
                ('updated_at', models.IntegerField(default=0)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Store',
            },
        ),
    ]
