# Generated by Django 2.0.2 on 2019-12-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='contact',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(null=True, upload_to='store'),
        ),
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
