# Generated by Django 2.0.2 on 2019-12-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.TextField(default=''),
        ),
    ]
