# Generated by Django 2.0.2 on 2020-03-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='qrcode',
            field=models.ImageField(null=True, upload_to='store/qrcode'),
        ),
    ]
