# Generated by Django 2.0.2 on 2020-03-18 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200316_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(null=True, upload_to='store_offers')),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
            options={
                'verbose_name_plural': 'StoreOffers',
            },
        ),
    ]
