# Generated by Django 2.0.2 on 2020-03-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_storeoffers'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeoffers',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
