# Generated by Django 2.0.2 on 2020-03-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_storeoffers_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeoffers',
            name='created_at',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storeoffers',
            name='updated_at',
            field=models.IntegerField(default=0),
        ),
    ]
