# Generated by Django 2.0.2 on 2020-03-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200318_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeoffers',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeoffers',
            name='percentage',
            field=models.IntegerField(default=1),
        ),
    ]
