# Generated by Django 2.0.2 on 2020-03-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200324_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeoffers',
            old_name='percentage',
            new_name='points',
        ),
    ]
